steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - hello_world
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --allow-unauthenticated
  - --gen2
  - --entry-point=hello_world
  - --egress-settings=all
  - --ingress-settings=internal-only
  - --memory=4GB
  - --timeout=3600s
  - --min-instances=0
  - --max-instances=1
  - --region=us-central1
  - --vpc-connector=None